# Generated by Django 2.1.4 on 2019-01-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ques_rules',
            fields=[
                ('rules_id', models.IntegerField(primary_key=True, serialize=False)),
                ('static_id', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('correct_id', models.IntegerField()),
                ('wrong_id', models.IntegerField()),
            ],
        ),
    ]
