# Generated by Django 2.1.4 on 2019-01-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ques_create',
            fields=[
                ('parentid', models.CharField(max_length=250)),
                ('staticid', models.AutoField(primary_key=True, serialize=False)),
                ('qid', models.CharField(max_length=250)),
                ('question', models.TextField()),
                ('a', models.CharField(max_length=250)),
                ('b', models.CharField(max_length=250)),
                ('c', models.CharField(max_length=250)),
                ('d', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
                ('importance', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default='LOW', max_length=6)),
                ('complexity', models.PositiveIntegerField(default=0)),
                ('time', models.CharField(max_length=200)),
                ('marks', models.CharField(max_length=200)),
                ('foundation', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('core', models.CharField(max_length=250)),
                ('exam', models.CharField(max_length=250)),
                ('fscore', models.CharField(max_length=250)),
                ('sscore', models.CharField(max_length=250)),
                ('cscore', models.CharField(max_length=250)),
                ('escore', models.CharField(max_length=250)),
                ('tag', models.CharField(max_length=250)),
            ],
        ),
    ]
