# Generated by Django 2.1.4 on 2019-01-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbuilder', '0002_ques_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_topic',
            fields=[
                ('static_id', models.IntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField()),
                ('main_id', models.IntegerField()),
                ('topic_name', models.CharField(max_length=250)),
                ('count_subtopic', models.IntegerField()),
                ('count_ques', models.IntegerField()),
                ('importance', models.CharField(max_length=100)),
                ('complexity', models.CharField(max_length=100)),
                ('prerequisite', models.CharField(max_length=250)),
            ],
        ),
    ]
