# Generated by Django 2.1.4 on 2019-01-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbuilder', '0003_create_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques_create',
            name='staticid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
